### ISSUE TITLE
Unnecessary Error

### ISSUE THREAD

**Issue by rasekar2000** [arvindr21/myRESTApp#2]
Hi Arvind,

 When I followed the steps. It works nicely.. Appreciated.. But i am seeing this error in the log.. Even though its not impacting the application functionally , it appears annoying.. At the same time , my guess is that it may be the case , because of the latest version of the node_modules. But if you could take a look with recent versions,  that would be great.

  Thanks in advance.

Regards,
Raj

Error: Forbidden
    at createError (ngClient/node_modules/gulp-connect/node_modules/connect/node_modules/serve-index/index.js:188:13)
    at Object.directory [as handle](ngClient/node_modules/gulp-connect/node_modules/connect/node_modules/serve-index/index.js:100:46)
    at next (ngClient/node_modules/gulp-connect/node_modules/connect/lib/proto.js:194:15)
    at SendStream.error (ngClient/node_modules/gulp-connect/node_modules/connect/node_modules/serve-static/index.js:86:37)
    at SendStream.EventEmitter.emit (events.js:95:17)
    at SendStream.error (ngClient/node_modules/gulp-connect/node_modules/connect/node_modules/serve-static/node_modules/send/lib/send.js:172:51)
    at SendStream.onStatError (ngClient/node_modules/gulp-connect/node_modules/connect/node_modules/serve-static/node_modules/send/lib/send.js:285:48)
    at ngClient/node_modules/gulp-connect/node_modules/connect/node_modules/serve-static/node_modules/send/lib/send.js:378:26
    at Object.oncomplete (fs.js:107:15)

**Comment by JoseRFJuniorLLMs** [comment]
Error: Not Found
   at /home/jr/Documentos/PROJETOS_ANGULAR/wsRest/server/server.js:34:13
   at Layer.handle [as handle_request](/home/jr/Documentos/PROJETOS_ANGULAR/wsRest/server/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/jr/Documentos/PROJETOS_ANGULAR/wsRest/server/node_modules/express/lib/router/index.js:312:13)
   at /home/jr/Documentos/PROJETOS_ANGULAR/wsRest/server/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/home/jr/Documentos/PROJETOS_ANGULAR/wsRest/server/node_modules/express/lib/router/index.js:330:12)
   at next (/home/jr/Documentos/PROJETOS_ANGULAR/wsRest/server/node_modules/express/lib/router/index.js:271:10)
   at /home/jr/Documentos/PROJETOS_ANGULAR/wsRest/server/node_modules/express/lib/router/index.js:618:15
   at next (/home/jr/Documentos/PROJETOS_ANGULAR/wsRest/server/node_modules/express/lib/router/index.js:256:14)
   at Function.handle (/home/jr/Documentos/PROJETOS_ANGULAR/wsRest/server/node_modules/express/lib/router/index.js:176:3)
   at router (/home/jr/Documentos/PROJETOS_ANGULAR/wsRest/server/node_modules/express/lib/router/index.js:46:12)
